var musicSrcArr =[
'Jain - Lil Mama.mp3',
'Bebe Rexha - Ferrari.mp3',
'Imagine Dragons - Natural.mp3',
'马良、孙茜茹 - 往后余生.mp3',
'宋冬野 - 安和桥.mp3',
'于文文 - 体面.mp3',
'张靓颖 - Dream It Possible.mp3',
'赵雷 - 成都.mp3',
'Alan Walker、K-391、Tungevaag、Mangoo - Play.mp3',
'BEYOND - 光辉岁月.mp3',
'BEYOND - 海阔天空.mp3',
'Christine Welch - 一百万个可能.mp3',
'Consoul Trainin - Take Me to Infinity (Radio Edit).mp3',
'Deepmaniak - Something Just Like This (Remix).mp3',
'DJ Maxwell - VIVI NELL’ARIA (Extended).mp3',
'G.E.M.邓紫棋 - 我的秘密.mp3',
'JAEFOREAL - 我是好人.mp3',
'K-391、Alan Walker、Julie Bergan、胜利 - Ignite.mp3',
'Katie Sky - Monsters.mp3',
'Lola Coca - GQ.mp3',
'Oh The Larceny - Man on a Mission.mp3',
'Poppy - Choke.mp3',
'Poppy - Moshi Moshi.mp3',
'Queen - We Will Rock You.mp3',
'SHAUN - Way Back Home.mp3',
'Tungevaag - Wicked Wonderland.mp3',
'陈硕子 - 当我要走的时候 (正式版).mp3',
'黑龙 - 38度6.mp3',
'李袁杰 - 离人愁.mp3',
'孙语赛、萧全 - 不仅仅是喜欢.mp3',
'徐秉龙、沈以诚 - 白羊.mp3',
'丫蛋蛋换个心情做自己、崔铭嘉 - 口是心非.mp3',
'音阙诗听、王梓钰 - 红昭愿 (高音质版).mp3',
'银临、Aki阿杰 - 牵丝戏.mp3',
'展展与罗罗 - 沙漠骆驼.mp3',
'周笔畅 - 最美的期待.mp3',
'庄心妍 - 走着走着就散了.mp3',
'李荣浩 - 戒烟.mp3',
'梁博 - 男孩 (Live).mp3'
];
var musicName = [];
for (var i = 0; i < musicSrcArr.length; i++) {
	musicName[i] = musicSrcArr[i].replace(/(\.mp3\b|\.flac\b)/, "");
};